### ISSUE TITLE
Support for torchaudio in Pytorch container

### ISSUE THREAD

**Issue by bbalaji-ucsd** [aws/deep-learning-containers#1109]
When I try installing torchaudio and import it, it gives me the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension  # noqa: F401
  File "/opt/conda/lib/python3.6/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/opt/conda/lib/python3.6/site-packages/torchaudio/extension/extension.py", line 11, in _init_extension
    _init_script_module(ext)
  File "/opt/conda/lib/python3.6/site-packages/torchaudio/extension/extension.py", line 18, in _init_script_module
    torch.classes.load_library(path)
  File "/opt/conda/lib/python3.6/site-packages/torch/_classes.py", line 46, in load_library
    torch.ops.load_library(path)
  File "/opt/conda/lib/python3.6/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/lib/python3.6/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```

**Comment by elektrozitrone** [comment]
it is a different symbol, when installing `torchaudio==0.9.1` on `763104351884.dkr.ecr.eu-central-1.amazonaws.com/pytorch-training:1.9.1-cpu-py38-ubuntu20.04`:

```
OSError: /opt/conda/lib/python3.8/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```

but probably the same problem. as commented in #1533 it is probably an incompatibility in the build settings. unfortunately i could not yet find informations on how the pytorch binary wheels are built, as in the Dockerfiles they are only downloaded from s3.

could you provide documentation on how to build torchaudio for the sagemaker containers? or even better provide a build in s3 like for torch and torchvision packages? or best just include a compatible torchaudio build in the sagemaker images?

the torchaudio package does not have additional install-time dependencies and does not add much to the image size.

**Comment by Unlicensed-driver-ljx** [comment]
源码构建看我的安装那篇https://blog.csdn.net/weixin_46151178?type=blog

**Comment by tejaschumbalkar** [comment]
Hello @bbalaji-ucsd,
`torchaudio` is now installed by default on [supported](https://aws.amazon.com/releasenotes/dlc-support-policy/) PyTorch Training DLCs. You can checkout our latest PyTorch DLC v2.2
`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:2.2.0-gpu-py310-cu121-ubuntu20.04-sagemaker-v1.0`
