### ISSUE TITLE
[bug] torchaudio broken in torch 1.9.1 inference image

### ISSUE THREAD

**Issue by marcelgwerder** [aws/deep-learning-containers#1533]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [x] (If applicable) I've attached the script to reproduce the bug
- [x] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [x] (If applicable) I've documented below the tests I've run on the DLC image
- [x] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html

*Concise Description:*

Importing `torchaudio` in the image fails with an undefined symbol exception. I tried to use this image for OpenNMT-py and the library imports some torchaudio modules which causes this exception.

Steps to reproduce:

```
➜  docker pull 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.9.1-cpu-py38-ubuntu20.04
1.9.1-cpu-py38-ubuntu20.04: Pulling from pytorch-inference
Digest: sha256:39a48df9ac3e9f6381980827b40a5b19e11928c7ef3d8b7eacb4e437f263b69c
Status: Image is up to date for 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.9.1-cpu-py38-ubuntu20.04
763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.9.1-cpu-py38-ubuntu20.04
➜  docker run -it --rm --entrypoint /bin/bash 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.9.1-cpu-py38-ubuntu20.04
root@06c87239cc2a:/# ipython
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torchaudio
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-4cf0a64f61c0> in <module>
----> 1 import torchaudio

/opt/conda/lib/python3.8/site-packages/torchaudio/__init__.py in <module>
----> 1 from . import extension  # noqa: F401
      2 from torchaudio._internal import module_utils as _mod_utils  # noqa: F401
      3 from torchaudio import (
      4     compliance,
      5     datasets,

/opt/conda/lib/python3.8/site-packages/torchaudio/extension/__init__.py in <module>
      3 )
      4
----> 5 _init_extension()
      6
      7 del _init_extension

/opt/conda/lib/python3.8/site-packages/torchaudio/extension/extension.py in _init_extension()
      9     ext = 'torchaudio._torchaudio'
     10     if _mod_utils.is_module_available(ext):
---> 11         _init_script_module(ext)
     12         import torchaudio._torchaudio  # noqa
     13     else:

/opt/conda/lib/python3.8/site-packages/torchaudio/extension/extension.py in _init_script_module(module)
     17 def _init_script_module(module):
     18     path = importlib.util.find_spec(module).origin
---> 19     torch.classes.load_library(path)
     20     torch.ops.load_library(path)

/opt/conda/lib/python3.8/site-packages/torch/_classes.py in load_library(self, path)
     44             path (str): A path to a shared library to load.
     45         """
---> 46         torch.ops.load_library(path)
     47
     48 # The classes "namespace"

/opt/conda/lib/python3.8/site-packages/torch/_ops.py in load_library(self, path)
    102             # static (global) initialization code in order to register custom
    103             # operators with the JIT.
--> 104             ctypes.CDLL(path)
    105         self.loaded_libraries.add(path)
    106

/opt/conda/lib/python3.8/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    371
    372         if handle is None:
--> 373             self._handle = _dlopen(self._name, mode)
    374         else:
    375             self._handle = handle

OSError: /opt/conda/lib/python3.8/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```

*DLC image/dockerfile:*

763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:1.9.1-cpu-py38-ubuntu20.04
1.9.1-cpu-py38-ubuntu20.04

*Current behavior:*

Import of `torchaudio` fails with undefined symbol error.

*Expected behavior:*

Import of `torchaudio` works without errors.

**Comment by marcelgwerder** [comment]
Related to #1109

**Comment by ntw-au** [comment]
Exactly the same missing symbol error occurs when using the `pytorch-training:1.7.1-gpu-py36-cu110-ubuntu18.04` image with `open3d` 0.13.0, installed from `pip`.

```Traceback (most recent call last):
  File "/opt/ml/code/basic_test.py", line 11, in <module>
    ml3d = importlib.import_module(f'open3d.ml.{args.backend}')
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.6/site-packages/open3d/ml/torch/__init__.py", line 111, in <module>
    raise _load_except
  File "/opt/conda/lib/python3.6/site-packages/open3d/ml/torch/__init__.py", line 100, in <module>
    _torch.ops.load_library(_lp)
  File "/opt/conda/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/lib/python3.6/site-packages/open3d/cpu/open3d_torch_ops.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv```

**Comment by ntw-au** [comment]
Further investigations suggest that this may be caused by C++11 binary API incompatibility. The Deep Learning Containers seem to build everything with `_GLIBCXX_USE_CXX11_ABI=1`, whereas `pip` packages are typically built with the older API. (See also http://www.open3d.org/docs/release/compilation.html#ml-module)

**Comment by tejaschumbalkar** [comment]
Hello @marcelgwerder 

`torchaudio` import issue is no longer seen on the latest PyTorch Inference DLC. You can checkout our latest PyTorch v2.1 DLC `763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference:2.1.0-cpu-py310-ubuntu20.04-sagemaker`

**Comment by arjkesh** [comment]
Closing issue due to lack of response. Please feel free to reopen if this issue persists.
